unit ssl_const;

interface

const
  NID_undef = 0;
  NID_rsaEncryption = 6;
  NID_rsa = 19;
  NID_dhKeyAgreement = 28;
  NID_dsaWithSHA = 66;
  NID_dsa_2 = 67;
  NID_dsaWithSHA1_2 = 70;
  NID_dsaWithSHA1 = 113;
  NID_dsa = 116;
  NID_hmac = 855;
  NID_cmac = 894;
  NID_X9_62_id_ecPublicKey = 408;

const
  ASIdentifierChoice_inherit = 0;
  ASIdentifierChoice_asIdsOrRanges = 1;

  IPAddressOrRange_addressPrefix = 0;
  IPAddressOrRange_addressRange = 1;

  IPAddressChoice_inherit = 0;
  IPAddressChoice_addressesOrRanges = 1;

  SHA_LBLOCK = 16;
  SHA_CBLOCK = 64;
  SHA_DIGEST_LENGTH = 20;
  SHA_LAST_BLOCK = (SHA_CBLOCK - 8);
  SHA256_CBLOCK = (SHA_LBLOCK * 4);
  SHA224_DIGEST_LENGTH = 28;
  SHA256_DIGEST_LENGTH = 32;
  SHA384_DIGEST_LENGTH = 48;
  SHA512_DIGEST_LENGTH = 64;
  SHA512_CBLOCK = (SHA_LBLOCK * 8);

  EVP_MAX_MD_SIZE = 64;
  EVP_MAX_KEY_LENGTH = 32;
  EVP_MAX_IV_LENGTH = 16;
  EVP_MAX_BLOCK_LENGTH = 32;

const
  BIO_F_ACPT_STATE = 100;
  BIO_F_BIO_ACCEPT = 101;
  BIO_F_BIO_BER_GET_HEADER = 102;
  BIO_F_BIO_CALLBACK_CTRL = 131;
  BIO_F_BIO_CTRL = 103;
  BIO_F_BIO_GETHOSTBYNAME = 120;
  BIO_F_BIO_GETS = 104;
  BIO_F_BIO_GET_ACCEPT_SOCKET = 105;
  BIO_F_BIO_GET_HOST_IP = 106;
  BIO_F_BIO_GET_PORT = 107;
  BIO_F_BIO_MAKE_PAIR = 121;
  BIO_F_BIO_NEW = 108;
  BIO_F_BIO_NEW_FILE = 109;
  BIO_F_BIO_NEW_MEM_BUF = 126;
  BIO_F_BIO_NREAD = 123;
  BIO_F_BIO_NREAD0 = 124;
  BIO_F_BIO_NWRITE = 125;
  BIO_F_BIO_NWRITE0 = 122;
  BIO_F_BIO_PUTS = 110;
  BIO_F_BIO_READ = 111;
  BIO_F_BIO_SOCK_INIT = 112;
  BIO_F_BIO_WRITE = 113;
  BIO_F_BUFFER_CTRL = 114;
  BIO_F_CONN_CTRL = 127;
  BIO_F_CONN_STATE = 115;
  BIO_F_DGRAM_SCTP_READ = 132;
  BIO_F_FILE_CTRL = 116;
  BIO_F_FILE_READ = 130;
  BIO_F_LINEBUFFER_CTRL = 129;
  BIO_F_MEM_READ = 128;
  BIO_F_MEM_WRITE = 117;
  BIO_F_SSL_NEW = 118;
  BIO_F_WSASTARTUP = 119;

  BIO_R_ACCEPT_ERROR = 100;
  BIO_R_BAD_FOPEN_MODE = 101;
  BIO_R_BAD_HOSTNAME_LOOKUP = 102;
  BIO_R_BROKEN_PIPE = 124;
  BIO_R_CONNECT_ERROR = 103;
  BIO_R_EOF_ON_MEMORY_BIO = 127;
  BIO_R_ERROR_SETTING_NBIO = 104;
  BIO_R_ERROR_SETTING_NBIO_ON_ACCEPTED_SOCKET = 105;
  BIO_R_ERROR_SETTING_NBIO_ON_ACCEPT_SOCKET = 106;
  BIO_R_GETHOSTBYNAME_ADDR_IS_NOT_AF_INET = 107;
  BIO_R_INVALID_ARGUMENT = 125;
  BIO_R_INVALID_IP_ADDRESS = 108;
  BIO_R_IN_USE = 123;
  BIO_R_KEEPALIVE = 109;
  BIO_R_NBIO_CONNECT_ERROR = 110;
  BIO_R_NO_ACCEPT_PORT_SPECIFIED = 111;
  BIO_R_NO_HOSTNAME_SPECIFIED = 112;
  BIO_R_NO_PORT_DEFINED = 113;
  BIO_R_NO_PORT_SPECIFIED = 114;
  BIO_R_NO_SUCH_FILE = 128;
  BIO_R_NULL_PARAMETER = 115;
  BIO_R_TAG_MISMATCH = 116;
  BIO_R_UNABLE_TO_BIND_SOCKET = 117;
  BIO_R_UNABLE_TO_CREATE_SOCKET = 118;
  BIO_R_UNABLE_TO_LISTEN_SOCKET = 119;
  BIO_R_UNINITIALIZED = 120;
  BIO_R_UNSUPPORTED_METHOD = 121;
  BIO_R_WRITE_TO_READ_ONLY_BIO = 126;
  BIO_R_WSASTARTUP = 122;

implementation

end.
